# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import rental_pb2 as proto_dot_rental__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/rental_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextbookRentalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStock = channel.unary_unary(
                '/rental.TextbookRentalService/CheckStock',
                request_serializer=proto_dot_rental__pb2.StockRequest.SerializeToString,
                response_deserializer=proto_dot_rental__pb2.StockResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/rental.TextbookRentalService/GetBook',
                request_serializer=proto_dot_rental__pb2.BookRequest.SerializeToString,
                response_deserializer=proto_dot_rental__pb2.BookResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_unary(
                '/rental.TextbookRentalService/SearchBooks',
                request_serializer=proto_dot_rental__pb2.SearchRequest.SerializeToString,
                response_deserializer=proto_dot_rental__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.RentBook = channel.unary_unary(
                '/rental.TextbookRentalService/RentBook',
                request_serializer=proto_dot_rental__pb2.RentRequest.SerializeToString,
                response_deserializer=proto_dot_rental__pb2.RentResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/rental.TextbookRentalService/ReturnBook',
                request_serializer=proto_dot_rental__pb2.ReturnRequest.SerializeToString,
                response_deserializer=proto_dot_rental__pb2.ReturnResponse.FromString,
                _registered_method=True)


class TextbookRentalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RentBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextbookRentalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=proto_dot_rental__pb2.StockRequest.FromString,
                    response_serializer=proto_dot_rental__pb2.StockResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=proto_dot_rental__pb2.BookRequest.FromString,
                    response_serializer=proto_dot_rental__pb2.BookResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=proto_dot_rental__pb2.SearchRequest.FromString,
                    response_serializer=proto_dot_rental__pb2.SearchResponse.SerializeToString,
            ),
            'RentBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RentBook,
                    request_deserializer=proto_dot_rental__pb2.RentRequest.FromString,
                    response_serializer=proto_dot_rental__pb2.RentResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=proto_dot_rental__pb2.ReturnRequest.FromString,
                    response_serializer=proto_dot_rental__pb2.ReturnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rental.TextbookRentalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rental.TextbookRentalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextbookRentalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.TextbookRentalService/CheckStock',
            proto_dot_rental__pb2.StockRequest.SerializeToString,
            proto_dot_rental__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.TextbookRentalService/GetBook',
            proto_dot_rental__pb2.BookRequest.SerializeToString,
            proto_dot_rental__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.TextbookRentalService/SearchBooks',
            proto_dot_rental__pb2.SearchRequest.SerializeToString,
            proto_dot_rental__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RentBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.TextbookRentalService/RentBook',
            proto_dot_rental__pb2.RentRequest.SerializeToString,
            proto_dot_rental__pb2.RentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rental.TextbookRentalService/ReturnBook',
            proto_dot_rental__pb2.ReturnRequest.SerializeToString,
            proto_dot_rental__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
