# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/rental.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/rental.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/rental.proto\x12\x06rental\"\x1c\n\x0cStockRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"D\n\rStockResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\x14\n\x0cis_available\x18\x03 \x01(\x08\"\x1b\n\x0b\x42ookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"w\n\x0c\x42ookResponse\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\rprice_per_day\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x14\n\x0cis_available\x18\x06 \x01(\x08\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"5\n\x0eSearchResponse\x12#\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x14.rental.BookResponse\"=\n\x0bRentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x0c\n\x04isbn\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x03 \x01(\x05\"X\n\x0cRentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\trental_id\x18\x02 \x01(\t\x12\x13\n\x0btotal_price\x18\x03 \x01(\x01\x12\x0f\n\x07message\x18\x04 \x01(\t\"\"\n\rReturnRequest\x12\x11\n\trental_id\x18\x01 \x01(\t\"2\n\x0eReturnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x02\n\x15TextbookRentalService\x12\x39\n\nCheckStock\x12\x14.rental.StockRequest\x1a\x15.rental.StockResponse\x12\x34\n\x07GetBook\x12\x13.rental.BookRequest\x1a\x14.rental.BookResponse\x12<\n\x0bSearchBooks\x12\x15.rental.SearchRequest\x1a\x16.rental.SearchResponse\x12\x35\n\x08RentBook\x12\x13.rental.RentRequest\x1a\x14.rental.RentResponse\x12;\n\nReturnBook\x12\x15.rental.ReturnRequest\x1a\x16.rental.ReturnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rental_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=30
  _globals['_STOCKREQUEST']._serialized_end=58
  _globals['_STOCKRESPONSE']._serialized_start=60
  _globals['_STOCKRESPONSE']._serialized_end=128
  _globals['_BOOKREQUEST']._serialized_start=130
  _globals['_BOOKREQUEST']._serialized_end=157
  _globals['_BOOKRESPONSE']._serialized_start=159
  _globals['_BOOKRESPONSE']._serialized_end=278
  _globals['_SEARCHREQUEST']._serialized_start=280
  _globals['_SEARCHREQUEST']._serialized_end=310
  _globals['_SEARCHRESPONSE']._serialized_start=312
  _globals['_SEARCHRESPONSE']._serialized_end=365
  _globals['_RENTREQUEST']._serialized_start=367
  _globals['_RENTREQUEST']._serialized_end=428
  _globals['_RENTRESPONSE']._serialized_start=430
  _globals['_RENTRESPONSE']._serialized_end=518
  _globals['_RETURNREQUEST']._serialized_start=520
  _globals['_RETURNREQUEST']._serialized_end=554
  _globals['_RETURNRESPONSE']._serialized_start=556
  _globals['_RETURNRESPONSE']._serialized_end=606
  _globals['_TEXTBOOKRENTALSERVICE']._serialized_start=609
  _globals['_TEXTBOOKRENTALSERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
